name: Build Multi-Platform Pure Release
on: workflow_dispatch

jobs:
  # 安卓正式版编译：去除 DEBUG 按钮和飘带
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        working-directory: ./simple_live_app
        run: flutter pub get

      - name: Build Android Release
        working-directory: ./simple_live_app
        # 使用 --release 模式实现“纯净版”，--no-signing 绕过签名文件校验
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons --no-pub --no-signing

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLive-Samsung-Pure-Edition
          path: simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8
